[package]
name = "libjxl-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
link-cplusplus = "1"

[build-dependencies]
bindgen = "0.69.2"
pkg-config = "0.3.29"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(google3)'] }

[features]
libjxl = []
