name: Build and Run Tests (avm Feature)
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

# Cancel the workflow if a new one is triggered from the same PR, branch, or tag, except on main.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build-and-run-tests-avm-feature:
    name: "Build and Run Tests on ${{ matrix.os }} (avm Features)"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    env:
      CC: clang
      CXX: clang++

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      # Build aom.
      - uses: ./.github/actions/setup-deps

      # Build avm.
      - name: Cache external avm dependency
        id: cache-ext-avm
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: sys/avm-sys
          key: ${{ runner.os }}-${{ hashFiles('.github/workflows/build-and-run-tests-avm.yml', 'sys/avm-sys/build.rs', 'sys/avm-sys/Cargo.toml', 'sys/avm-sys/avm.cmd', 'sys/avm-sys/wrapper.h') }}
      - uses: jwlawson/actions-setup-cmake@d06b37b47cfd043ec794ffa3e40e0b6b5858a7ec # v1.14.2
        if: steps.cache-ext-avm.outputs.cache-hit != 'true'
      - uses: ilammy/setup-nasm@13cbeb366c45c4379d3478cdcbadd8295feb5028 # v1.5.1
        if: steps.cache-ext-avm.outputs.cache-hit != 'true'
      - uses: seanmiddleditch/gha-setup-ninja@8b297075da4cd2a5f1fd21fe011b499edf06e9d2 # v4
        if: steps.cache-ext-avm.outputs.cache-hit != 'true'
      - name: Download and build avm
        if: steps.cache-ext-avm.outputs.cache-hit != 'true'
        working-directory: ./sys/avm-sys
        run: ./avm.cmd

      - name: Build and run the Rust tests
        run: cargo test --features aom,avm -- --skip test_conformance
